module.exports = Object.freeze({
   NOT_FOUND: "NOT_FOUND",
   FORBIDDEN: "FORBIDDEN",
   DUPLICATE_DATA: "DUPLICATE_DATA",
   MISSING_DATA: "MISSING_DATA",
   MISSING_ATTRIBUTES: "MISSING_ATTRIBUTES"
});